### ISSUE TITLE
Current addon package seems to be broken

### ISSUE THREAD

**Issue by steveszc** [rwjblue/ember-cli-template-lint#185] opened 2016-12-14 20:59 UTC
I'm sure this is related to a change in one of the addon's dependencies, but as of this afternoon including this addon in an ember app breaks the app's build. I've been able to reproduce with a fresh Ember-cli 2.10 app, as well as in Ember Twiddle. 

Adding ember-cli-template-lint to the twiddle.json in Ember twiddle throws the following build error in Ember Twiddle.
Installing ember-cli-template-lint  and running ember build throws a very similar error.

Twiddle with reproduction:
https://ember-twiddle.com/fedaa44f27821882e00a30192c18a181

```
Addon ember-cli-template-lint is still building...
Addon ember-cli-template-lint encountered a build error:(anonymous function) @ ember-twiddle-7e98278a5aca3eeb5fbce9ff0e104f45.js:2
ember-twiddle-7e98278a5aca3eeb5fbce9ff0e104f45.js:2 Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: error: Your local changes to the following files would be overwritten by checkout:
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: test/fixtures/JSX/multiline-crlf-text.js
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: test/fixtures/comment/migrated_0011.js
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: test/fixtures/expression/primary/literal/string/migrated_0017.js
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: test/fixtures/invalid-syntax/migrated_0153.js
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: test/fixtures/invalid-syntax/migrated_0155.js
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: test/fixtures/invalid-syntax/migrated_0159.js
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: Please, commit your changes or stash them before you can switch branches.
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: Aborting
git checkout a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd: Installed packages for tooling via npm.
installing ember-cli-template-lint
  create .template-lintrc.js
Installed addon package.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot find module 'esprima/' from '/addon-builder/node_modules/ember-cli-template-lint/node_modules/ember-template-lint/node_modules/glimmer-engine/node_modules/qunit/node_modules/istanbul/'
Error: Cannot find module 'esprima/' from '/addon-builder/node_modules/ember-cli-template-lint/node_modules/ember-template-lint/node_modules/glimmer-engine/node_modules/qunit/node_modules/istanbul/'
    at Function.module.exports [as sync] (/addon-builder/node_modules/resolve/lib/sync.js:33:11)
    at resolvePkg (/addon-builder/node_modules/hash-for-dep/lib/resolve-pkg.js:20:18)
    at pkg (/addon-builder/node_modules/hash-for-dep/lib/pkg.js:17:20)
    at again (/addon-builder/node_modules/hash-for-dep/lib/deps-for.js:18:22)
    at /addon-builder/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/addon-builder/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /addon-builder/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/addon-builder/node_modules/hash-for-dep/lib/deps-for.js:26:55)

No addon.js created
```

**Comment by mitchlloyd** [comment] 2016-12-15 18:36
After a fresh clone of a repo today I'm getting an error as well, but mine is a bit different:

```
Cannot find module 'istanbul/' from '/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-template-lint/node_modules/ember-template-lint/node_modules/glimmer-engine/node_modules/qunit/'
Error: Cannot find module 'istanbul/' from '/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-template-lint/node_modules/ember-template-lint/node_modules/glimmer-engine/node_modules/qunit/'
    at Function.module.exports [as sync] (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/node_modules/resolve/lib/sync.js:36:11)
    at resolvePkg (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/resolve-pkg.js:20:18)
    at pkg (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/pkg.js:17:20)
    at again (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:18:22)
    at /Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:26:55)
    at /Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:27:7
    at Array.forEach (native)
    at again (/Users/mitch/projects/aptible/dashboard-private-master/node_modules/ember-cli-htmlbars-inline-precompile/node_modules/hash-for-dep/lib/deps-for.js:26:55)
```

**Comment by mitchlloyd** [comment] 2016-12-15 23:59
Just now I reinstalled and it seems like the issue has been resolved.

**Comment by jrjohnson** [comment] 2017-04-10 21:29
I'm getting the error 
`Cannot find module 'istanbul/' from 'node_modules/glimmer-engine/node_modules/qunit/`
again today.

**Comment by atomaras** [comment] 2017-04-26 20:53
having same issue as @jrjohnson

**Comment by SharavanaPrasad** [comment] 2017-04-27 13:31
@jrjohnson @atomaras , I have got this error too... `istanbul` is one of the dependencies of qunit, which is a dependecy of `glimmer-engine` consumed by `ember-template-lint` which is originally consumed by `ember-cli-template-lint@0.5.2`. The problem I faced with istanbul -> this dependency is specified by it's repository url, rather than "name":"version", format. So npm install (running behind a proxy) fails to install this particular package and hence the build will fail, due to a missing package.

One way to get around this issue is do a `npm --proxy=http://userproxy-server:*port_no* --registry=http://registry.npmjs.org install`, with proxy set and make sure it points to the global npm registry.  

If the qunit is updated to the latest version(which has this istanbul =>  "istanbul": "0.4.5" in package.json), this issue would be solved.

**Comment by Alonski** [comment] 2017-04-27 16:31
@SharavanaPrasad I get this too.
I am not behind a proxy.
Is there a way to install this addon directly?

**Comment by SharavanaPrasad** [comment] 2017-04-28 03:32
@Alonski , try installing `npm install ember-cli-template-lint@0.5.2`, check whether if the package installs all of it's dependencies (including `istanbul`). If not try again with `npm install --registry:http://www.npmjs.org ember-cli-template-lint@0.5.2`. If both didn't work, then it is probably due to your network issue only.

**Comment by SharavanaPrasad** [comment] 2017-06-24 09:41
@Alonski @jrjohnson The issue is now fixed for me with the latest release of the package `0.7.0`.
Thanks to @rwjblue 👍

**Comment by rwjblue** [comment] 2017-06-24 13:48
Awesome thank you for confirming!

**Closed by rwjblue** 2017-06-24 13:48 UTC
